language: node_js
os: linux
node_js:
- 10.16.3
script: npm test
deploy:
    edge: true
    provider: npm
    email: victor.ndambakuwa@customweb.com
    api_token: "$NPM_API_KEY"
    on:
        tags: true
        repo: wallee-payment/typescript-sdk
    skip_cleanup: true